---
# yamllint disable rule:line-length
default_language_version:
  python: python3.8
repos:
  - repo: git://github.com/bridgecrewio/checkov
    rev: 2.0.153
    hooks:
      - id: checkov
        verbose: true
        entry: checkov -d .