---
# yamllint disable rule:line-length
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.61.1  # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: serverless/.*\.(json|yml|yaml)$
  - repo: https://github.com/bridgecrewio/checkov
    rev: 2.1.32
    hooks:
      - id: checkov
        verbose: true
        entry: checkov -d .