---
# yamllint disable rule:line-length
name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: read-all

env:
  terraform: 1.3.0
  branch: main
  name: Checkov GitHub Action
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list    
      - name: checkov 
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          soft_fail: true
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list