---
# yamllint disable rule:line-length
name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: read-all

env:
  terraform: 1.3.0
  branch: main
  name: Checkov GitHub Action
jobs:
  terraform:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list    
      - name: checkov 
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
      - name: az cli
        uses: azure/cli@v1.0.7
        with:
          inlineScript: az storage account list
        env:
          CHECKOV_RESULTS: ""
          
